;;; agent-pane-tests.el --- Tests for agent-pane -*- lexical-binding: t; -*-

(require 'ert)
(require 'agent-pane)

;;; Code:

(ert-deftest agent-pane-rerender-creates-input-marker ()
  (with-temp-buffer
    (agent-pane-mode)
    (should (markerp agent-pane--input-marker))
    (should (<= (marker-position agent-pane--input-marker) (point-max)))))

(ert-deftest agent-pane-mode-enables-visual-line-mode ()
  (with-temp-buffer
    (agent-pane-mode)
    (should visual-line-mode)
    (should-not truncate-lines)))

(ert-deftest agent-pane-submit-appends-messages ()
  (with-temp-buffer
    (agent-pane-mode)
    (goto-char (point-max))
    (insert "hello")
    (agent-pane-submit)
    (let ((msgs (map-elt agent-pane--state :messages)))
      ;; In batch mode, agent-pane does not spawn ACP processes, so submitting
      ;; only adds the user message.
      (should (= (length msgs) 1))
      (should (eq (map-elt (nth 0 msgs) :role) 'user))
      (should (equal (map-elt (nth 0 msgs) :text) "hello"))
      (should (equal (map-elt agent-pane--state :input-history) '("hello"))))))

(ert-deftest agent-pane-input-history-prev-next-roundtrip ()
  (with-temp-buffer
    (agent-pane-mode)
    (goto-char (point-max))
    (insert "first")
    (agent-pane-submit)
    (goto-char (point-max))
    (insert "second")
    (agent-pane-submit)
    (goto-char (point-max))
    (insert "draft")
    (agent-pane-input-history-prev)
    (should (equal (agent-pane--input-text) "second"))
    (agent-pane-input-history-prev)
    (should (equal (agent-pane--input-text) "first"))
    (agent-pane-input-history-next)
    (should (equal (agent-pane--input-text) "second"))
    (agent-pane-input-history-next)
    (should (equal (agent-pane--input-text) "draft"))))

(ert-deftest agent-pane-copy-last-user-to-input-works ()
  (with-temp-buffer
    (agent-pane-mode)
    (goto-char (point-max))
    (insert "first")
    (agent-pane-submit)
    (goto-char (point-max))
    (insert "second")
    (agent-pane-submit)
    (agent-pane-copy-last-user-to-input)
    (should (equal (agent-pane--input-text) "second"))))

(ert-deftest agent-pane-edit-input-commit-updates-chat-input ()
  (let ((agent-pane-input-editor-buffer-name "*agent-pane input test*"))
    (unwind-protect
        (with-temp-buffer
          (agent-pane-mode)
          (goto-char (point-max))
          (insert "hello")
          (cl-letf (((symbol-function 'pop-to-buffer)
                     (lambda (&rest _args) nil)))
            (agent-pane-edit-input))
          (with-current-buffer agent-pane-input-editor-buffer-name
            (goto-char (point-max))
            (insert "\nworld")
            (cl-letf (((symbol-function 'pop-to-buffer)
                       (lambda (&rest _args) nil)))
              (agent-pane-input-editor-commit)))
          (should (equal (agent-pane--input-text) "hello\nworld")))
      (ignore-errors (kill-buffer "*agent-pane input test*")))))

(ert-deftest agent-pane-jump-next-previous-message-works ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'user :text "one")
    (agent-pane--append-message* :role 'assistant :text "two")
    (agent-pane--rerender)
    (goto-char (point-min))
    (agent-pane-jump-next-message)
    (should (eq (map-elt (get-text-property (point) 'agent-pane-message) :role) 'user))
    (agent-pane-jump-next-message)
    (should (eq (map-elt (get-text-property (point) 'agent-pane-message) :role) 'assistant))
    (agent-pane-jump-previous-message)
    (should (eq (map-elt (get-text-property (point) 'agent-pane-message) :role) 'user))))

(ert-deftest agent-pane-copy-last-tool-output-copies-output-section ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'tool
                                 :text "id: tc1\nstatus: completed\n\noutput:\nok")
    (let (copied)
      (cl-letf (((symbol-function 'kill-new)
                 (lambda (s &optional _replace)
                   (setq copied s))))
        (agent-pane-copy-last-tool-output)
        (should (equal copied "ok"))))))

(ert-deftest agent-pane-copy-code-block-at-point-copies-body ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant
                                 :text "```elisp\n(+ 1 2)\n```")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (search-forward "(+ 1 2)" nil t))
    (let (copied)
      (cl-letf (((symbol-function 'kill-new)
                 (lambda (s &optional _replace)
                   (setq copied s))))
        (agent-pane-copy-code-block-at-point)
        (should (equal copied "(+ 1 2)"))))))

(ert-deftest agent-pane-toggle-fold-message-at-point-toggles-overlay ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant :text "line 1\nline 2")
    (agent-pane--rerender)
    (agent-pane-jump-next-message)
    (let ((msg (get-text-property (point) 'agent-pane-message)))
      (agent-pane-toggle-fold-message-at-point)
      (let ((ov (gethash msg agent-pane--fold-overlays)))
        (should (overlayp ov))
        (should (eq (overlay-get ov 'invisible) 'agent-pane-fold)))
      (agent-pane-toggle-fold-message-at-point)
      (should-not (gethash msg agent-pane--fold-overlays)))))

(ert-deftest agent-pane-ensure-acp-client-applies-config-overrides ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-acp-client-maker nil)
          (agent-pane-acp-provider 'codex)
          (agent-pane-codex-command '("codex-acp" "--flag"))
          (agent-pane-codex-config-overrides '("model_reasoning_effort=\"high\""
                                               "sandbox_mode=\"danger-full-access\"")))
      (map-put! agent-pane--state :client nil)
      (agent-pane--ensure-acp-client)
      (let ((client (map-elt agent-pane--state :client)))
        (should (equal (map-elt client :command) "codex-acp"))
        (should (equal (map-elt client :command-params)
                       '("--flag"
                         "-c" "model_reasoning_effort=\"high\""
                         "-c" "sandbox_mode=\"danger-full-access\"")))))))

(ert-deftest agent-pane-acp-command-and-params-supports-copilot-provider ()
  (let ((agent-pane-acp-provider 'copilot)
        (agent-pane-copilot-command '("copilot" "--acp" "--foo"))
        (agent-pane-codex-config-overrides '("ignored=\"1\"")))
    (should (equal (agent-pane--acp-command-and-params)
                   '("copilot" "--acp" "--foo")))))

(ert-deftest agent-pane-acp-command-and-params-supports-claude-provider ()
  (let ((agent-pane-acp-provider 'claude-code)
        (agent-pane-claude-code-command '("claude-code-acp" "--bar"))
        (agent-pane-codex-config-overrides '("ignored=\"1\"")))
    (should (equal (agent-pane--acp-command-and-params)
                   '("claude-code-acp" "--bar")))))

(ert-deftest agent-pane-acp-environment-follows-provider ()
  (let ((agent-pane-codex-environment '("A=1"))
        (agent-pane-copilot-environment '("B=2"))
        (agent-pane-claude-code-environment '("C=3")))
    (let ((agent-pane-acp-provider 'codex))
      (should (equal (agent-pane--acp-environment) '("A=1"))))
    (let ((agent-pane-acp-provider 'copilot))
      (should (equal (agent-pane--acp-environment) '("B=2"))))
    (let ((agent-pane-acp-provider 'claude-code))
      (should (equal (agent-pane--acp-environment) '("C=3"))))))

(ert-deftest agent-pane-set-acp-provider-resets-connection-state ()
  (with-temp-buffer
    (agent-pane-mode)
    (map-put! agent-pane--state :client '((dummy . t)))
    (map-put! agent-pane--state :session-id "s1")
    (map-put! agent-pane--state :subscribed t)
    (let ((agent-pane-acp-provider 'codex)
          (agent-pane-auth-method-id "chatgpt"))
      (agent-pane-set-acp-provider 'copilot)
      (should (eq agent-pane-acp-provider 'copilot))
      (should (null agent-pane-auth-method-id))
      (should (null (map-elt agent-pane--state :client)))
      (should (null (map-elt agent-pane--state :session-id)))
      (should (null (map-elt agent-pane--state :subscribed))))))

(ert-deftest agent-pane-set-acp-provider-keeps-active-run-state ()
  (with-temp-buffer
    (agent-pane-mode)
    (map-put! agent-pane--state :client 'dummy-client)
    (map-put! agent-pane--state :session-id "s1")
    (map-put! agent-pane--state :in-progress 'streaming)
    (let ((agent-pane-acp-provider 'codex)
          (agent-pane-auth-method-id "chatgpt")
          messages)
      (cl-letf (((symbol-function 'message)
                 (lambda (fmt &rest args)
                   (push (apply #'format fmt args) messages))))
        (agent-pane-set-acp-provider 'copilot))
      (should (eq agent-pane-acp-provider 'copilot))
      (should (null agent-pane-auth-method-id))
      (should (eq (map-elt agent-pane--state :client) 'dummy-client))
      (should (equal (map-elt agent-pane--state :session-id) "s1"))
      (should (cl-some (lambda (m)
                         (string-match-p "will apply after current run" m))
                       messages)))))

(ert-deftest agent-pane-set-session-model-updates-active-session ()
  (with-temp-buffer
    (agent-pane-mode)
    (map-put! agent-pane--state :client (list (cons :agent-pane-fake t)))
    (map-put! agent-pane--state :session-id "s1")
    (let (sent-request)
      (cl-letf (((symbol-function 'agent-pane--acp-send-request)
                 (lambda (&rest args)
                   (setq sent-request (plist-get args :request))
                   (funcall (plist-get args :on-success) '((ok . t))))))
        (agent-pane-set-session-model "gpt-5")
        (should (equal agent-pane-session-model-id "gpt-5"))
        (should (equal (map-elt sent-request :method) "session/set_model"))
        (should (equal (or (map-nested-elt sent-request '(params modelId))
                           (map-nested-elt sent-request '(:params modelId)))
                       "gpt-5"))))))

(ert-deftest agent-pane-set-session-model-clears-preference ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-session-model-id "gpt-5"))
      (agent-pane-set-session-model "")
      (should (null agent-pane-session-model-id)))))

(ert-deftest agent-pane-set-session-model-handshakes-when-session-missing ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-enable-acp t)
          (noninteractive nil)
          handshake-called
          applied-model)
      (cl-letf (((symbol-function 'agent-pane--handshake)
                 (lambda (on-ready)
                   (setq handshake-called t)
                   (map-put! agent-pane--state :client 'dummy-client)
                   (map-put! agent-pane--state :session-id "s1")
                   (funcall on-ready)))
                ((symbol-function 'agent-pane--set-session-model)
                 (lambda (model-id &optional on-success _on-failure)
                   (setq applied-model model-id)
                   (when (functionp on-success)
                     (funcall on-success '((ok . t))))))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (agent-pane-set-session-model "gpt-5")
        (should handshake-called)
        (should (equal applied-model "gpt-5"))))))

(ert-deftest agent-pane-set-session-model-interactive-uses-protocol-model-list ()
  (with-temp-buffer
    (agent-pane-mode)
    (map-put! agent-pane--state :available-model-ids '("gpt-5" "gpt-5-mini"))
    (map-put! agent-pane--state :client (list (cons :agent-pane-fake t)))
    (map-put! agent-pane--state :session-id "s1")
    (let (completion-prompt completion-collection read-string-called applied-model)
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (prompt collection &rest _args)
                   (setq completion-prompt prompt)
                   (setq completion-collection collection)
                   "gpt-5-mini"))
                ((symbol-function 'read-string)
                 (lambda (&rest _args)
                   (setq read-string-called t)
                   "unused"))
                ((symbol-function 'agent-pane--set-session-model)
                 (lambda (model-id &optional on-success _on-failure)
                   (setq applied-model model-id)
                   (when (functionp on-success)
                     (funcall on-success '((ok . t))))))
                ((symbol-function 'message)
                 (lambda (&rest _args) nil)))
        (call-interactively #'agent-pane-set-session-model)
        (should (string-match-p "protocol list" completion-prompt))
        (should (equal completion-collection '("gpt-5" "gpt-5-mini")))
        (should-not read-string-called)
        (should (equal applied-model "gpt-5-mini"))
        (should (equal agent-pane-session-model-id "gpt-5-mini"))))))

(ert-deftest agent-pane-on-notification-config-options-update-caches-model-list ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--on-notification
     '((jsonrpc . "2.0")
       (method . "session/update")
       (params . ((sessionId . "s1")
                  (update . ((sessionUpdate . "config_options_update")
                             (configOptions . [((id . "model")
                                                (category . "model")
                                                (currentValue . "gpt-5")
                                                (options . [((value . "gpt-5"))
                                                            ((value . "gpt-5-mini"))]))])))))))
    (should (equal (map-elt agent-pane--state :available-model-ids)
                   '("gpt-5" "gpt-5-mini")))
    (should (equal (map-elt agent-pane--state :current-model-id) "gpt-5"))))

(ert-deftest agent-pane-extract-diff-info-supports-standard-content ()
  (let* ((tool-call '((content . ((type . "diff")
                                  (path . "src/main.el")
                                  (oldText . "a\nb\n")
                                  (newText . "a\nc\n")))))
         (diff (agent-pane--extract-diff-info tool-call)))
    (should (equal (plist-get diff :file) "src/main.el"))
    (should (equal (plist-get diff :old) "a\nb\n"))
    (should (equal (plist-get diff :new) "a\nc\n"))))

(ert-deftest agent-pane-extract-diff-info-supports-nested-content-wrapper ()
  (let* ((tool-call '((content . [((type . "content")
                                   (content . ((type . "diff")
                                               (path . "src/main.el")
                                               (oldText . "x\n")
                                               (newText . "y\n"))))])))
         (diff (agent-pane--extract-diff-info tool-call)))
    (should (equal (plist-get diff :file) "src/main.el"))
    (should (equal (plist-get diff :old) "x\n"))
    (should (equal (plist-get diff :new) "y\n"))))

(ert-deftest agent-pane-merge-tool-output-preserves-complete-stream ()
  (should (equal (agent-pane--merge-tool-output nil "abc") "abc"))
  (should (equal (agent-pane--merge-tool-output "abc" "abcdef") "abcdef"))
  (should (equal (agent-pane--merge-tool-output "abc" "def") "abcdef"))
  (should (equal (agent-pane--merge-tool-output "abcdef" "") "abcdef")))

(ert-deftest agent-pane-tool-call-content-string-skips-diff-items ()
  (let* ((content [((type . "diff")
                    (path . "src/main.el")
                    (oldText . "old")
                    (newText . "new"))
                   ((type . "text")
                    (content . ((text . "hello"))))])
         (s (agent-pane--tool-call-content->string content)))
    (should (equal s "hello"))))

(ert-deftest agent-pane-tool-call-content-string-handles-wrapped-map ()
  (let* ((content '((type . "content")
                    (content . ((type . "text")
                                (text . "Codex says hi")
                                (_meta . ((stage . "analysis")))))
                    (uri . "codex://tool")))
         (s (agent-pane--tool-call-content->string content)))
    (should (equal s "Codex says hi"))))

(ert-deftest agent-pane-tool-call-content-string-handles-single-text-pair ()
  (let* ((content '((text . "Hello")))
         (s (agent-pane--tool-call-content->string content)))
    (should (equal s "Hello"))))

(ert-deftest agent-pane-tool-call-content-string-handles-thinking-field ()
  (let* ((content '((type . "reasoning")
                    (title . "Planning")
                    (thinking . ((type . "text")
                                 (text . "Detailed reasoning text")))))
         (s (agent-pane--tool-call-content->string content)))
    (should (equal s "Detailed reasoning text"))))

(ert-deftest agent-pane-view-diff-at-point-opens-tool-diff ()
  (with-temp-buffer
    (agent-pane-mode)
    (let* ((tool-id "tc_1")
           (diff '(:file "src/main.el" :old "a\n" :new "a\nb\n"))
           (idx (agent-pane--append-message* :role 'tool :title "bash" :text "changes pending"))
           shown)
      (puthash tool-id idx (map-elt agent-pane--state :tool-call-msg-index))
      (puthash tool-id (list :toolCallId tool-id :diff diff) (map-elt agent-pane--state :tool-calls))
      (agent-pane--rerender)
      (agent-pane-jump-next-message)
      (cl-letf (((symbol-function 'agent-pane--show-diff)
                 (lambda (d &optional _title)
                   (setq shown d))))
        (agent-pane-view-diff-at-point)
        (should (equal shown diff))))))

(ert-deftest agent-pane-show-diff-diff-mode-renders-without-external-diff ()
  (let ((diff '(:file "src/main.el" :old "a\nb\n" :new "a\nc\n"))
        shown-buf)
    (unwind-protect
        (cl-letf (((symbol-function 'diff-no-select)
                   (lambda (&rest _args)
                     (ert-fail "agent-pane--show-diff-diff-mode should not call diff-no-select")))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (buf &rest _args)
                     (setq shown-buf buf)
                     buf)))
          (agent-pane--show-diff-diff-mode diff "Diff title")
          (with-current-buffer shown-buf
            (should (eq major-mode 'diff-mode))
            (should (string-match-p
                     (regexp-quote
                      (string-join '("--- a/src/main.el"
                                     "+++ b/src/main.el"
                                     "@@ -1,2 +1,2 @@"
                                     "-a"
                                     "-b"
                                     "+a"
                                     "+c"
                                     "")
                                   "\n"))
                     (buffer-string)))))
      (when (buffer-live-p shown-buf)
        (kill-buffer shown-buf)))))

(ert-deftest agent-pane-tool-call-entry-to-text-shows-last-five-lines ()
  (let* ((agent-pane-tool-output-preview-lines 5)
         (entry (list :title "bash"
                      :command "echo hello"
                      :output (string-join '("l1" "l2" "l3" "l4" "l5" "l6" "l7") "\n")))
         (text (agent-pane--tool-call-entry-to-text entry)))
    (should (string-match-p "^tool: bash echo hello" text))
    (should (string-match-p "output (latest 5 lines, 2 omitted):" text))
    (should-not (string-match-p "l1" text))
    (should (string-match-p "l3" text))
    (should (string-match-p "l7" text))))

(ert-deftest agent-pane-tool-call-entry-to-text-shows-full-output-when-toggled ()
  (let* ((agent-pane--tool-output-full-mode t)
         (entry (list :title "bash"
                      :command "echo hello"
                      :output (string-join '("l1" "l2" "l3") "\n")))
         (text (agent-pane--tool-call-entry-to-text entry)))
    (should (string-match-p "output (full):" text))
    (should (string-match-p "l1" text))
    (should (string-match-p "l3" text))
    (should-not (string-match-p "latest" text))))

(ert-deftest agent-pane-tool-call-entry-to-text-includes-params ()
  (let* ((entry (list :title "functions.shell_command"
                      :command "shell_command"
                      :params '((command . "Get-ChildItem -Force")
                                (workdir . "c:/Projects/agent-mode"))))
         (text (agent-pane--tool-call-entry-to-text entry)))
    (should (string-match-p "^tool: functions\\.shell_command shell_command" text))
    (should (string-match-p "params:" text))
    (should (string-match-p "Get-ChildItem -Force" text))
    (should (string-match-p "workdir" text))))

(ert-deftest agent-pane-tool-call-display-title-avoids-opaque-call-id ()
  (let* ((entry (list :toolCallId "call_utRvJt9VSAqk8sir0WFmIpxH"
                      :title "call_utRvJt9VSAqk8sir0WFmIpxH"
                      :kind "functions.shell_command"
                      :params '((command . "Get-ChildItem -Force"))))
         (title (agent-pane--tool-call-display-title entry)))
    (should (string-match-p "Get-ChildItem -Force" title))
    (should-not (string-match-p (rx string-start "call_") title))))

(ert-deftest agent-pane-tool-call-display-title-falls-back-to-generic-for-opaque-id ()
  (let* ((entry (list :toolCallId "call_utRvJt9VSAqk8sir0WFmIpxH"
                      :title "call_utRvJt9VSAqk8sir0WFmIpxH"))
         (title (agent-pane--tool-call-display-title entry)))
    (should (equal title "tool call"))))

(ert-deftest agent-pane-toggle-tool-output-mode-refreshes-tool-messages ()
  (with-temp-buffer
    (agent-pane-mode)
    (let* ((tool-id "tc_1")
           (idx (agent-pane--append-message* :role 'tool :title "bash" :text "placeholder"))
           (entry (list :toolCallId tool-id
                        :title "bash"
                        :command "echo hello"
                        :output (string-join '("l1" "l2" "l3" "l4" "l5" "l6") "\n"))))
      (puthash tool-id idx (map-elt agent-pane--state :tool-call-msg-index))
      (puthash tool-id entry (map-elt agent-pane--state :tool-calls))
      (agent-pane--refresh-tool-call-messages)
      (agent-pane--rerender)
      (should-not agent-pane--tool-output-full-mode)
      (should (string-match-p "output (latest" (buffer-string)))
      (agent-pane-toggle-tool-output-mode)
      (should agent-pane--tool-output-full-mode)
      (should (string-match-p "output (full):" (buffer-string)))
      (agent-pane-toggle-tool-output-mode)
      (should-not agent-pane--tool-output-full-mode)
      (should (string-match-p "output (latest" (buffer-string))))))

(ert-deftest agent-pane-tool-message-has-invocation-and-output-faces ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'tool
                                 :title "bash"
                                 :text "tool: bash echo hi\n\noutput (latest 5 lines):\nok")
    (agent-pane--rerender)
    (goto-char (point-min))
    (search-forward "tool: bash")
    (let ((line-beg (line-beginning-position)))
      (should (eq (get-text-property line-beg 'face)
                  'agent-pane-tool-invocation-block)))
    (search-forward "output (latest 5 lines):")
    (let ((line-beg (line-beginning-position)))
      (should (eq (get-text-property line-beg 'face)
                  'agent-pane-tool-output-block)))))

(ert-deftest agent-pane-tool-message-full-output-header-has-output-face ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'tool
                                 :title "bash"
                                 :text "tool: bash echo hi\n\noutput (full):\nok")
    (agent-pane--rerender)
    (goto-char (point-min))
    (search-forward "output (full):")
    (let ((line-beg (line-beginning-position)))
      (should (eq (get-text-property line-beg 'face)
                  'agent-pane-tool-output-block)))))

(ert-deftest agent-pane-tool-block-faces-extend-to-window-edge ()
  (should (eq (face-attribute 'agent-pane-tool-invocation-block :extend nil 'default) t))
  (should (eq (face-attribute 'agent-pane-tool-output-block :extend nil 'default) t)))

(ert-deftest agent-pane-exit-keybindings-present ()
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c ."))
              #'agent-pane-dispatch))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c C-."))
              #'agent-pane-dispatch))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c C-q"))
              #'agent-pane-exit))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c C-v"))
              #'agent-pane-toggle-header-details-anywhere))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c v"))
              #'agent-pane-toggle-header-details-anywhere))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c m"))
              #'agent-pane-set-session-model))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c C-m"))
              #'agent-pane-set-session-model))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c d"))
              #'agent-pane-view-diff-at-point-anywhere))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c C-d"))
              #'agent-pane-view-diff-at-point-anywhere))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c o"))
              #'agent-pane-toggle-tool-output-mode))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c C-o"))
              #'agent-pane-toggle-tool-output-mode))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c i"))
              #'agent-pane-edit-input))
  (should (eq (lookup-key agent-pane-mode-map (kbd "C-c C-i"))
              #'agent-pane-edit-input))
  (should (eq (lookup-key agent-pane-sessions-mode-map (kbd "q"))
              #'agent-pane-exit))
  (should (eq (lookup-key agent-pane-input-editor-mode-map (kbd "C-c v"))
              #'agent-pane-toggle-header-details-anywhere))
  (should (eq (lookup-key agent-pane-input-editor-mode-map (kbd "C-c C-v"))
              #'agent-pane-toggle-header-details-anywhere))
  (should (eq (lookup-key agent-pane-input-editor-mode-map (kbd "C-c d"))
              #'agent-pane-view-diff-at-point-anywhere))
  (should (eq (lookup-key agent-pane-input-editor-mode-map (kbd "C-c C-d"))
              #'agent-pane-view-diff-at-point-anywhere)))

(ert-deftest agent-pane-header-summary-is-compact-when-collapsed ()
  (let ((agent-pane-show-acp-header t)
        (agent-pane-header-details-collapsed t)
        (agent-pane-acp-provider 'copilot)
        (agent-pane-session-model-id "gpt-5"))
    (with-temp-buffer
      (agent-pane-mode)
      (agent-pane--rerender)
      (let ((s (buffer-string)))
        (should (string-match-p "provider=copilot" s))
        (should (string-match-p "model=gpt-5" s))
        (should-not (string-match-p "authMethods:" s))))))

(ert-deftest agent-pane-toggle-header-details-anywhere-works-from-non-chat-buffer ()
  (let ((chat (get-buffer-create "*agent-pane header-toggle-anywhere*")))
    (unwind-protect
        (progn
          (with-current-buffer chat
            (agent-pane-mode)
            (setq-local agent-pane--header-details-collapsed t))
          (with-temp-buffer
            (special-mode)
            (cl-letf (((symbol-function 'agent-pane--find-chat-buffer-anywhere)
                       (lambda () chat)))
              (agent-pane-toggle-header-details-anywhere)))
          (with-current-buffer chat
            (should-not agent-pane--header-details-collapsed)))
      (when (buffer-live-p chat)
        (kill-buffer chat)))))

(ert-deftest agent-pane-toggle-header-details-expands-debug-section ()
  (let ((agent-pane-show-acp-header t)
        (agent-pane-header-details-collapsed t))
    (with-temp-buffer
      (agent-pane-mode)
      (map-put! agent-pane--state :init-result '((protocolVersion . 1)
                                                 (agentCapabilities . ((loadSession . t)
                                                                       (promptCapabilities . ((image . t)))))))
      (agent-pane--rerender)
      (should-not (string-match-p "Server: protocolVersion=" (buffer-string)))
      (agent-pane-toggle-header-details)
      (should (string-match-p "Server: protocolVersion=" (buffer-string))))))

(ert-deftest agent-pane-cancel-clears-queued-prompts ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-enable-acp t)
          (noninteractive nil)
          sent)
      (map-put! agent-pane--state :client 'dummy-client)
      (map-put! agent-pane--state :session-id "s1")
      (map-put! agent-pane--state :prompt-in-flight t)
      (map-put! agent-pane--state :in-progress 'streaming)
      (map-put! agent-pane--state :prompt-queue '("keep?" "drop?"))
      (map-put! agent-pane--state :queued-prompts '(ignore))
      (cl-letf (((symbol-function 'agent-pane--acp-send-notification)
                 (lambda (&rest args)
                   (setq sent (plist-get args :notification)))))
        (agent-pane-cancel))
      (should (equal (map-elt sent :method) "session/cancel"))
      (should (null (map-elt agent-pane--state :prompt-in-flight)))
      (should (null (map-elt agent-pane--state :in-progress)))
      (should (null (map-elt agent-pane--state :prompt-queue)))
      (should (null (map-elt agent-pane--state :prompt-queue-message-indices)))
      (should (null (map-elt agent-pane--state :queued-prompts))))))

(ert-deftest agent-pane-exit-closes-app-buffers ()
  (let* ((chat (get-buffer-create agent-pane-buffer-name))
         (sessions (get-buffer-create agent-pane-sessions-buffer-name))
         (input (get-buffer-create agent-pane-input-editor-buffer-name))
         (client '((dummy . t)))
         shutdown-client)
    (unwind-protect
        (progn
          (with-current-buffer chat
            (agent-pane-mode)
            (map-put! agent-pane--state :client client))
          (cl-letf (((symbol-function 'acp-shutdown)
                     (lambda (&key client)
                       (setq shutdown-client client))))
            (agent-pane-exit))
          (should (equal shutdown-client client))
          (should-not (buffer-live-p chat))
          (should-not (buffer-live-p sessions))
          (should-not (buffer-live-p input)))
      (ignore-errors (kill-buffer chat))
      (ignore-errors (kill-buffer sessions))
      (ignore-errors (kill-buffer input)))))

(ert-deftest agent-pane-exit-closes-all-chat-buffers ()
  (let* ((chat-main (get-buffer-create agent-pane-buffer-name))
         (chat-new (generate-new-buffer "*agent-pane<new>*"))
         (sessions (get-buffer-create agent-pane-sessions-buffer-name))
         (input (get-buffer-create agent-pane-input-editor-buffer-name))
         (client-main '((main . t)))
         (client-new '((new . t)))
         shutdown-clients)
    (unwind-protect
        (progn
          (with-current-buffer chat-main
            (agent-pane-mode)
            (map-put! agent-pane--state :client client-main))
          (with-current-buffer chat-new
            (agent-pane-mode)
            (map-put! agent-pane--state :client client-new))
          (cl-letf (((symbol-function 'acp-shutdown)
                     (lambda (&key client)
                       (push client shutdown-clients))))
            (agent-pane-exit))
          (should (member client-main shutdown-clients))
          (should (member client-new shutdown-clients))
          (should (= (length shutdown-clients) 2))
          (should-not (buffer-live-p chat-main))
          (should-not (buffer-live-p chat-new))
          (should-not (buffer-live-p sessions))
          (should-not (buffer-live-p input)))
      (ignore-errors (kill-buffer chat-main))
      (ignore-errors (kill-buffer chat-new))
      (ignore-errors (kill-buffer sessions))
      (ignore-errors (kill-buffer input)))))

(ert-deftest agent-pane-ui-status-line-shows-waiting ()
  (let ((agent-pane-acp-provider 'copilot)
        (agent-pane-session-model-id "gpt-5"))
    (with-temp-buffer
      (agent-pane-mode)
      (map-put! agent-pane--state :in-progress 'waiting)
      (agent-pane--rerender)
      (let* ((start (marker-position agent-pane--status-beg-marker))
             (end (marker-position agent-pane--status-end-marker))
             (s (buffer-substring-no-properties start end))
             (h (format "%s" header-line-format)))
        (should (string-match-p "waiting for agent" s))
        (should (eq (get-text-property start 'face) 'agent-pane-status-busy))
        (should (string-match-p "waiting for agent" h))
        (should (string-match-p "provider=copilot" h))
        (should (string-match-p "model=gpt-5" h))))))

(ert-deftest agent-pane-prompt-queue-sends-followups-in-order ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-enable-acp t)
          (noninteractive nil)
          (sent nil))
      (map-put! agent-pane--state :client (list (cons :agent-pane-fake t)))
      (map-put! agent-pane--state :session-id "fake")
      (cl-letf (((symbol-function 'agent-pane--send-prompt)
                 (lambda (text)
                   ;; Assert we marked the prompt as in-flight before calling.
                   (should (map-elt agent-pane--state :prompt-in-flight))
                   (push text sent)
                   ;; Simulate end-of-turn.
                   (map-put! agent-pane--state :prompt-in-flight nil)
                   (map-put! agent-pane--state :in-progress nil)
                   (agent-pane--pump-prompt-queue))))
        (agent-pane--enqueue-prompt "first")
        (agent-pane--enqueue-prompt "second")
        (agent-pane--pump-prompt-queue)
        (should (equal (nreverse sent) '("first" "second")))
        (should (null (map-elt agent-pane--state :prompt-queue)))))))

(ert-deftest agent-pane-prompt-queue-clears-queued-flag-when-sent ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-enable-acp t)
          (noninteractive nil)
          sent)
      (map-put! agent-pane--state :client (list (cons :agent-pane-fake t)))
      (map-put! agent-pane--state :session-id "fake")
      (let ((idx (agent-pane--append-message* :role 'user :text "queued prompt")))
        (agent-pane--set-message-queued idx t)
        (agent-pane--enqueue-prompt "queued prompt" idx)
        (cl-letf (((symbol-function 'agent-pane--send-prompt)
                   (lambda (text)
                     (push text sent))))
          (agent-pane--pump-prompt-queue))
        (should (equal sent '("queued prompt")))
        (should-not (map-elt (nth idx (map-elt agent-pane--state :messages)) :queued))
        (should (null (map-elt agent-pane--state :prompt-queue-message-indices)))))))

(ert-deftest agent-pane-ui-keeps-queued-user-messages-at-bottom ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant :text "Current answer")
    (let ((queued-idx (agent-pane--append-message* :role 'user :text "Second request")))
      (agent-pane--set-message-queued queued-idx t)
      (agent-pane--rerender)
      (agent-pane--append-message* :role 'tool :title "shell_command" :text "tool: shell_command")
      (agent-pane--rerender)
      (let* ((s (buffer-string))
             (tool-pos (string-match (regexp-quote "Tool (shell_command):") s))
             (queued-pos (string-match (regexp-quote "You (queued):") s)))
        (should (numberp tool-pos))
        (should (numberp queued-pos))
        (should (< tool-pos queued-pos))))))

(ert-deftest agent-pane-submit-marks-followup-user-message-queued-while-streaming ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-enable-acp t)
          (noninteractive nil))
      (map-put! agent-pane--state :client (list (cons :agent-pane-fake t)))
      (map-put! agent-pane--state :session-id "s-stream")
      (map-put! agent-pane--state :in-progress 'streaming)
      (goto-char (point-max))
      (insert "follow-up")
      (agent-pane-submit)
      (let* ((msgs (map-elt agent-pane--state :messages))
             (m0 (nth 0 msgs)))
        (should (= (length msgs) 1))
        (should (eq (map-elt m0 :role) 'user))
        (should (map-elt m0 :queued))
        (should (equal (map-elt agent-pane--state :prompt-queue) '("follow-up")))
        (should (equal (map-elt agent-pane--state :prompt-queue-message-indices) '(0)))
        (should (string-match-p "You (queued):" (buffer-string)))))))

(ert-deftest agent-pane-prompt-queue-drains-after-external-connect ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-enable-acp t)
          (noninteractive nil)
          (agent-pane-auth-method-id nil)
          (sent nil)
          initialize-success
          session-new-success
          session-set-mode-success)
      (map-put! agent-pane--state :client (list (cons :agent-pane-fake t)))
      (cl-letf (((symbol-function 'agent-pane--ensure-acp-client)
                 (lambda () nil))
                ((symbol-function 'agent-pane--subscribe)
                 (lambda () nil))
                ((symbol-function 'agent-pane--acp-send-request)
                 (lambda (&rest args)
                   (let* ((request (plist-get args :request))
                          (on-success (plist-get args :on-success))
                          (method (or (map-elt request :method)
                                      (map-elt request 'method))))
                     (pcase method
                       ("initialize" (setq initialize-success on-success))
                       ("session/new" (setq session-new-success on-success))
                       ("session/set_mode" (setq session-set-mode-success on-success))
                       (_ (ert-fail (format "Unexpected ACP method: %S" method)))))))
                ((symbol-function 'agent-pane--send-prompt)
                 (lambda (text)
                   (push text sent))))
        ;; Simulate a connection started by another command (provider switch/model apply).
        (agent-pane--handshake (lambda () nil))
        (should (map-elt agent-pane--state :connecting))
        ;; Queue and pump while still connecting. This must register a post-connect drain.
        (agent-pane--enqueue-prompt "queued while connecting")
        (agent-pane--pump-prompt-queue)
        (agent-pane--pump-prompt-queue)
        (should (equal (map-elt agent-pane--state :queued-prompts)
                       '(agent-pane--pump-prompt-queue)))
        ;; Finish handshake and verify queued prompt is sent automatically.
        (funcall initialize-success '((protocolVersion . 1)))
        (funcall session-new-success '((sessionId . "s-connect")))
        (funcall session-set-mode-success '((ok . t)))
        (should (equal sent '("queued while connecting")))
        (should (null (map-elt agent-pane--state :prompt-queue)))))))

(ert-deftest agent-pane-ui-streaming-does-not-erase-buffer ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((orig (symbol-function 'erase-buffer))
          (erase-count 0))
      (cl-letf (((symbol-function 'erase-buffer)
                 (lambda ()
                   (setq erase-count (1+ erase-count))
                   (funcall orig))))
        (setq erase-count 0)
        (agent-pane--on-notification
         '((jsonrpc . "2.0")
           (method . "session/update")
           (params . ((sessionId . "s1")
                     (update . ((sessionUpdate . "agent_message_chunk")
                                (content . ((type . "text")
                                            (text . "Hi")))))))))
        (should (= erase-count 0))
        (should (string-match-p "Hi" (buffer-string)))))))

(ert-deftest agent-pane-ui-footer-stays-at-bottom-while-streaming ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--on-notification
     '((jsonrpc . "2.0")
       (method . "session/update")
       (params . ((sessionId . "s1")
                 (update . ((sessionUpdate . "agent_message_chunk")
                            (content . ((type . "text")
                                        (text . "Hello")))))))))
    (let* ((s (buffer-string))
           (pos-msg (string-match "Hello" s))
           (pos-footer (string-match "Type your message below" s)))
      (should (numberp pos-msg))
      (should (numberp pos-footer))
      ;; Footer should come after transcript.
      (should (< pos-msg pos-footer)))))

(ert-deftest agent-pane-transcripts-saved-on-submit ()
  (let ((agent-pane-save-transcripts 'always)
        (dir (make-temp-file "agent-pane-transcripts" t)))
    (unwind-protect
        (let ((agent-pane-transcript-directory dir))
          (with-temp-buffer
            (agent-pane-mode)
            (goto-char (point-max))
            (insert "hello transcript")
            (agent-pane-submit)
            (let ((file (map-elt agent-pane--state :transcript-file)))
              (should (stringp file))
              (should (file-exists-p file))
              (with-temp-buffer
                (insert-file-contents file)
                (should (string-match-p "hello transcript" (buffer-string)))
                (should (string-match-p "## User" (buffer-string)))))))
      (ignore-errors (delete-directory dir t)))))

(ert-deftest agent-pane-transcript-title-refreshes-sessions-sidebar ()
  (let ((agent-pane-save-transcripts 'always)
        (dir (make-temp-file "agent-pane-transcripts" t))
        (refresh-count 0))
    (unwind-protect
        (let ((agent-pane-transcript-directory dir))
          (cl-letf (((symbol-function 'agent-pane-sessions-refresh-if-visible)
                     (lambda ()
                       (setq refresh-count (1+ refresh-count)))))
            (with-temp-buffer
              (agent-pane-mode)
              (goto-char (point-max))
              (insert "Dynamic session title from first message")
              (agent-pane-submit)
              (let ((file (map-elt agent-pane--state :transcript-file)))
                (with-temp-buffer
                  (insert-file-contents file)
                  (should (string-match-p "- title: Dynamic session title from first message"
                                          (buffer-string)))))))
          (should (>= refresh-count 2)))
      (ignore-errors (delete-directory dir t)))))

(ert-deftest agent-pane-markdown-assistant-strong-is-colored ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant :text "Hi **there**")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (re-search-forward "\\*\\*there\\*\\*" nil t))
    (let ((beg (match-beginning 0))
          (end (match-end 0)))
      (should (eq (get-text-property beg 'face) 'agent-pane-markdown-delimiter))
      (should (eq (get-text-property beg 'invisible) 'agent-pane-markup))
      (should (eq (get-text-property (+ beg 2) 'face) 'agent-pane-markdown-strong-assistant))
      (should (eq (get-text-property (1- end) 'face) 'agent-pane-markdown-delimiter))
      (should (eq (get-text-property (1- end) 'invisible) 'agent-pane-markup)))))

(ert-deftest agent-pane-markdown-thought-strong-is-bold ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'thought :text "**bold**")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (re-search-forward "\\*\\*bold\\*\\*" nil t))
    (let ((beg (match-beginning 0)))
      (should (eq (get-text-property beg 'invisible) 'agent-pane-markup))
      (should (eq (get-text-property (+ beg 2) 'face) 'agent-pane-markdown-strong-thought)))))

(ert-deftest agent-pane-markdown-thought-body-has-thought-face ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'thought :text "plain thought text")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (search-forward "plain thought text" nil t))
    (should (eq (get-text-property (match-beginning 0) 'face)
                'agent-pane-role-thought))))

(ert-deftest agent-pane-tool-label-includes-title ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message*
     :role 'tool
     :title "shell_command"
     :text "tool: shell_command")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (search-forward "Tool (shell_command):" nil t))))

(ert-deftest agent-pane-markdown-strong-spans-chunk-boundary ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--on-notification
     '((jsonrpc . "2.0")
       (method . "session/update")
       (params . ((sessionId . "s1")
                 (update . ((sessionUpdate . "agent_message_chunk")
                            (content . ((type . "text")
                                        (text . "**Bo")))))))))
    (agent-pane--on-notification
     '((jsonrpc . "2.0")
       (method . "session/update")
       (params . ((sessionId . "s1")
                 (update . ((sessionUpdate . "agent_message_chunk")
                            (content . ((type . "text")
                                        (text . "ld**")))))))))
    (goto-char (point-min))
    (should (search-forward "Bold" nil t))
    (should (eq (get-text-property (1- (point)) 'face)
                'agent-pane-markdown-strong-assistant))
    (goto-char (point-min))
    (re-search-forward "\\*\\*Bold\\*\\*" nil t)
    (should (eq (get-text-property (match-beginning 0) 'invisible)
                'agent-pane-markup))))

(ert-deftest agent-pane-markdown-inline-code-spans-long-chunk-boundary ()
  (with-temp-buffer
    (agent-pane-mode)
    (let ((agent-pane-markdown-fontify-backtrack 10)
          (body (concat "Start `" (make-string 220 ?a))))
      (agent-pane--on-notification
       `((jsonrpc . "2.0")
         (method . "session/update")
         (params . ((sessionId . "s1")
                    (update . ((sessionUpdate . "agent_message_chunk")
                               (content . ((type . "text")
                                           (text . ,body)))))))))
      (agent-pane--on-notification
       '((jsonrpc . "2.0")
         (method . "session/update")
         (params . ((sessionId . "s1")
                    (update . ((sessionUpdate . "agent_message_chunk")
                               (content . ((type . "text")
                                           (text . "bbb` end")))))))))
      (goto-char (point-min))
      (should (re-search-forward "`a+bbb`" nil t))
      (let ((beg (match-beginning 0))
            (end (match-end 0)))
        (should (eq (get-text-property beg 'invisible) 'agent-pane-markup))
        (should (eq (get-text-property (1- end) 'invisible) 'agent-pane-markup))
        (should (eq (get-text-property (1+ beg) 'face)
                    'agent-pane-markdown-code))))))

(ert-deftest agent-pane-markdown-heading-is-fontified ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant :text "# Heading")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (re-search-forward "# Heading" nil t))
    (let ((beg (match-beginning 0)))
      (should (eq (get-text-property beg 'face) 'agent-pane-markdown-delimiter))
      (should (eq (get-text-property (+ beg 2) 'face) 'agent-pane-markdown-heading)))))

(ert-deftest agent-pane-markdown-list-marker-is-fontified ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant :text "- item")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (re-search-forward "- item" nil t))
    (let ((beg (match-beginning 0)))
      (should (eq (get-text-property beg 'face) 'agent-pane-markdown-list-marker)))))

(ert-deftest agent-pane-markdown-link-is-fontified ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant :text "[label](https://example.com)")
    (agent-pane--rerender)
    (goto-char (point-min))
    (should (re-search-forward "\\[label\\](https://example.com)" nil t))
    (let ((beg (match-beginning 0)))
      (should (eq (get-text-property beg 'face) 'agent-pane-markdown-delimiter))
      (should (eq (get-text-property (1+ beg) 'face) 'agent-pane-markdown-link-label))
      (should (eq (get-text-property beg 'invisible) 'agent-pane-markup)))))

(ert-deftest agent-pane-markdown-table-is-aligned-with-display-text ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message*
     :role 'assistant
     :text (string-join '("| Name | Score |"
                          "| --- | ---: |"
                          "| Al | 10 |"
                          "| Beatrice | 200 |")
                        "\n"))
    (agent-pane--rerender)
    (goto-char (point-min))
    (search-forward "Name")
    (let* ((line1 (line-beginning-position))
           (d1 (get-text-property line1 'display)))
      (forward-line 2)
      (let* ((line3 (line-beginning-position))
             (d3 (get-text-property line3 'display)))
        (should (stringp d1))
        (should (stringp d3))
        (should (string-match-p "| Al       |" d3))
        (should (= (string-width d1) (string-width d3)))))))

(ert-deftest agent-pane-markdown-table-has-table-face ()
  (with-temp-buffer
    (agent-pane-mode)
    (agent-pane--append-message* :role 'assistant
                                 :text "| A | B |\n| --- | --- |\n| 1 | 2 |")
    (agent-pane--rerender)
    (goto-char (point-min))
    (search-forward "| A | B |")
    (beginning-of-line)
    (let ((lbeg (point)))
      (should (eq (get-text-property lbeg 'face)
                  'agent-pane-markdown-table)))))

(provide 'agent-pane-tests)
;;; agent-pane-tests.el ends here
